name: run dbt Cloud job on push


# This filter says only run this job when there is a push to the main branch
# This works off the assumption that you've restrictred this branch to only all PRs to push to the deafult branch
# Update the name to match the name of your default branch
on:
  push:
    branches:
      - 'main'

jobs:

  cancel_running_slim_ci_jobs:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # running the step to cancel another other CI job runs that are running except the latest
      - name: Cancel another other CI runs that are running except the latest run
        id: cancel_stale_ci_runs
        uses: stevedow99/dbt-cloud-dynamic-ci-job-cancel-action@v1.1
        with:
          dbt_cloud_token: ${{ secrets.DBT_API_KEY }}
          dbt_cloud_account_id: 7767
          dbt_cloud_job_id: 48769

  # the job calls the dbt Cloud API to run a job
  run_dbt_cloud_build_base_and_production:
    name: Run build base and production
    runs-on: ubuntu-latest

  # Set the environment variables needed for the run
    env:
      DBT_ACCOUNT_ID: 7767 # enter your account id
      DBT_PROJECT_ID: 12062 # enter your project id
      DBT_PR_JOB_ID:  229781 # enter your job id
      DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      DBT_JOB_CAUSE: 'GitHub Pipeline CI Job' 
      DBT_JOB_BRANCH: ${{ github.ref_name }}

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: Run dbt Cloud job
        run: "python python/run_and_monitor_dbt_job.py"